name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Move to core folder and install dependencies
        run: |
          cd core
          npm install
        working-directory: ${{ github.workspace }}
        
      - name: Run tests for core
        run: npm test
        working-directory: ${{ github.workspace }}/core

      - name: Run ESLint for core
        run: npm run lint
        working-directory: ${{ github.workspace }}/core

      - name: Run Prettier for core
        run: npm run format
        working-directory: ${{ github.workspace }}/core

      - name: Move to example folder and install dependencies
        run: |
          cd example
          npm install
        working-directory: ${{ github.workspace }}
        
      - name: Run tests for example
        run: npm test
        working-directory: ${{ github.workspace }}/example

      - name: Run ESLint for example
        run: npm run lint
        working-directory: ${{ github.workspace }}/example

      - name: Run Prettier for example
        run: npm run format
        working-directory: ${{ github.workspace }}/example
